### ISSUE TITLE
Server down after testing rollback 1 line.

### ISSUE THREAD

**Issue by MHSimetra** [MisterTea/MAMEHub#314] opened 2015-01-07 20:45 UTC
Hey, Simetra here. I was testing out the "rollback 1" line with Jaku on a game of Darwin 4078, and some interesting things happened before I was kicked from MH, and now I'm getting a server is down message upon login attempt. I don't know why the rollback would have anything to do with this problem, but I was kicked in the middle of testing it so I tend to think it had something to do with it. According to Catweazle, everyone is having different problems with the rollback.

**Comment by MisterTea** [comment] 2015-01-07 23:44
Duplicate of #316

**Closed by MisterTea** 2015-01-07 23:44 UTC
