### ISSUE TITLE
Linux unable to connect on many Arcade systems

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#311] opened 2015-01-03 18:25 UTC
We already have a thread about checksum errors #248 and #281, but I thought I'd lift this one out specifically, because it makes Linux almost unplayable.

At first we thought it only happened between Linux <-> Windows, but now we tested between Linux users and they simply cannot connect at all (and nobody can connect to them) on certain (BIOS) arcade systems, such as:

Sega, Neogeo, Taoplan, Midway, old Konami (frogger), old Capcom.

The following checksum errors may occur:

CHECKSUM ERROR: 116 != 118 global/0/m_watchdog_counter (index: 40)
CHECKSUM ERROR: 189 != 110 stream/2/0/msamplerate (index: 751)
CHECKSUM ERROR: 239 != 44 DISCRETE/:konami/40000140/m_output (index: 451)

**Comment by MisterTea** [comment] 2015-01-03 19:43
Oh I know what it is. It's because I'm forcing single threaded on windows
but not Linux. I will fix it within the next 24 hours.

**Comment by MisterTea** [comment] 2015-01-04 04:36
Scratch that.  I checked and it looks like linux is also forced to one thread.

**Comment by MisterTea** [comment] 2015-01-04 04:59
Ok I believe the problem is from invalid ini files.  The first one is caused by one person setting watchdog to 1 in the ini file.  The second and third are caused by someone putting a value other than 48000 for the sample_rate (by default all of the ini files should set the sample rate to 48000).  Can you verify?

**Comment by Jaku2k** [comment] 2015-01-04 11:54
the sample rate was set to 48000 and watchdog to 0. I doubt the other user had it changed. Although the watchdog error wasnt from me I think.

**Comment by Gitweazle** [comment] 2015-01-04 15:19
The watchdog error was between JAM and Prinygod [1](http://pastebin.com/DjtdzTvB): Linux vs. Windows 7

I do recall akafox (Linux user) talking about lowering the samplerate because 48000 was kind of overkill for older games. In the beginning we connected and played together, but he later started to get connection problems. I will check with him.

**Comment by MisterTea** [comment] 2015-01-04 16:34
There are some games that override the sample rate but I can't imagine that
would be platform dependent. Let me know which game had the sample rate
problem and I'll investigate. Maybe it's a floating point issue?

**Comment by Gitweazle** [comment] 2015-01-04 23:28
Changing the bitrate does indeed cause the following errors. Nice!
CHECKSUM ERROR: 189 != 110 stream/2/0/msamplerate (index: 751)
CHECKSUM ERROR: 239 != 44 DISCRETE/:konami/40000140/m_output (index: 451) 

Other Linux specific checksums remain.

Quartet (Sega) gives:
CHECKSUM ERROR: 152 != 189 timer/timer_callback_a/0/m_start.attoseconds (index: 1719) 

Metal Slug (neogeo) and UMK3 (Midway) gives:
CHECKSUM ERROR: 71 != 190 memory/:maincpu/0/00200000-0028ffff (index: 25)

**Comment by Gitweazle** [comment] 2015-01-05 04:48
The Linux update fixed the connection problems. Thanks!

**Comment by Jaku2k** [comment] 2015-01-08 16:28
Its back

**Comment by MisterTea** [comment] 2015-01-08 16:37
Can someone tell me which checksum errors are back?

**Comment by Gitweazle** [comment] 2015-01-08 23:01
New important information: This is NOT a Linux specific issue.

All the checksum errors I have with Jaku happen with Simetra, who is just like me on WIndowx XP SP3. We compared hardware, and it seems that I am the only one with a single core.

Jaku and Simetra can connect to each other perfectly in these games.

----------------------------
- Rampage (Rev 3, 8/27/86) **[rampage.zip]**
CHECKSUM ERROR: 248 != 227 timer/static_timer_callback/1/m_period.attoseconds (index: 208) 

- Cotton (set 4, World, FD1094 317-0181a) **[cotton.zip]**
CHECKSUM ERROR: 252 != 253 timer/timer_callback_a/0/m_expire.attoseconds (index: 1617) 

- Golden Axe (set 4, Japan, FD1094 317-0121) **goldnaxej.zip**
CHECKSUM ERROR: 8 != 178 timer/timer_callback_a/0/m_start.attoseconds (index: 1615) 

Fixeight (Europe) **fixeight.zip**
CHECKSUM ERROR: 57 != 162 timer/v25_common_device::v25_timer_callback/2/m_period.attoseconds (index: 264) 

Turbo Force (old revision) **turbofrc.zip**
CHECKSUM ERROR: 15 != 160 timer/:ymsnd/0/0/m_start.attoseconds (index: 420)

Metal Slug X - Super Vehicle -001 (NGM-2500)(NGH-2500) **mslugx.zip**
CHECKSUM ERROR: 160 != 244 timer/:ymsnd/0/0/m_start.attoseconds (index: 486)

**Comment by Jaku2k** [comment] 2015-01-08 23:38
linux client connecting to windows host
neogeo
CHECKSUM ERROR: 145 != 215 memory/:maincpu/0/00100000-0010ffff (index: 28)

**Comment by MisterTea** [comment] 2015-01-09 01:22
@Gitweazle From the games you listed, do they all use chds?

**Comment by Gitweazle** [comment] 2015-01-09 01:29
None

**Comment by MisterTea** [comment] 2015-01-09 02:29
I'm closing this issue with this fix because I think at least some of the checksum errors are fixed by it.  Please open a new issue if you have additional checksum errors that aren't caught by this change.

**Closed** 2015-01-09 02:29 UTC
